### ISSUE TITLE
Interesting P99 latency results

### ISSUE THREAD

**Issue by nerdroychan** [ibraheemdev/papaya#19]
Hi there,

Thanks for publishing papaya. It is a nice work and the performance in read-intensive workloads is indeed amazing.

I would like to share an interesting, yet maybe not very important result that I observed during running papaya in my benchmark framework [kvbench](https://github.com/nerdroychan/kvbench). When running write-heavy workload with 1:1 r/w ratio and uniform random key distribution, the [latency](https://github.com/nerdroychan/kvbench/tree/9fdba59f7df794b4734f8a6ae81962a03f782be3/examples/latency) metrics I collected are as follows:

![results](https://raw.githubusercontent.com/nerdroychan/kvbench/9fdba59f7df794b4734f8a6ae81962a03f782be3/examples/latency/latency-writeheavy.png)

The average and P999 latency are normal. However the P99 latency of papaya seems abnormally high with 1 or 2 threads. Things seem to be normal with >4 threads. It does not hurt because average and P999 values are normal. But it looks like papaya has a different tail latency distribution compared to other maps with just 1 or 2 threads.

Not a real issue, but more of a sharing. ;)

**Comment by ibraheemdev** [comment]
Thanks for opening the issue! Yes, this is expected. Copying entries during a resize is more expensive for papaya because of the lack of locks. This makes resizing more expensive particularly when there aren't many threads to help out. You can somewhat control this by configuring the [`ResizeMode`](https://docs.rs/papaya/latest/papaya/enum.ResizeMode.html) depending on what you care about — large chunk sizes or blocking resizes can give you better throughput and average latency but worse tail latency.

As a side note, you might want to disable protection against stalled threads in your benchmark by setting [`Collector::epoch_frequency`](https://docs.rs/seize/latest/seize/struct.Collector.html#method.epoch_frequency) [to `None`](https://github.com/ibraheemdev/papaya/blob/ca9cf5e9cc88f6ac7425bc1235a7f62570d8afe0/benches/single_thread.rs#L32) if you're looking to measure the maximum throughput of operations.
